- name: "installing docker"
  apt: pkg=docker state=present

- name: "installing pip"
  apt: pkg=python-pip state=present

- name: "Install Docker Module for Python"
  pip:
   name: docker

- name: "Create project environment"
  file: 
   state=directory
   path={{ project_dir }}

- name: "Download Sources"
  get_url: url={{ url }} dest={{ project_dir }}/{{ file }}

- name: "Loading tarball into local repository"
  docker_image:
    name={{IBcontainername}}
    load_path={{project_dir}}/{{file}}
    source=load                        
    state=present
  
- name: "Start InfoBlox container"
  shell:
    sudo docker run -d --name blox.noa --network=host -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/infoblox/certs:/var/lib/infoblox/certs -v /etc/onprem.d/:/etc/onprem.d/ infobloxcto/onprem.agent:v3.3.6 --jointoken=rghbOtLO4C4Bc3MdvU8nj0sP8sxetCsexViCO_voM_o6
